### PR TITLE
ignore Topic if it does not exist, since plone.app.collection might be installed

### PR DESCRIPTION
**Pull request by cdw9**
The xml files in default/portal_placeful_workflow have the `Topic` content type, but this may not be available if plone.app.collection is installed

### CODE REVIEW

**Comment by jensens** [comment]
Does this target Plone 4.3?
May you please add a line to the change log?

**Comment by cdw9** [comment]
@jensens it is for Plone 4.3. I have updated the changelog to mention the change

**Comment by jensens** [comment]
for some reason http://jenkins.plone.org/job/pull-request-4.3/194/ does not report back to github

**Comment by jensens** [comment]
looks like jenkins is broken for 4.3 PRs, I filed an issue at plone/jenkins.plone.org#139

**Pull request merged**
